### ISSUE TITLE
getPMF of UpdateDoublesSketch is giving different results for same data

### ISSUE THREAD

**Issue by priyamgupta01** [apache/incubator-datasketches-java#288]
I am using tuple sketch to get the distribution of data by using Probability Histogram of values, For larger datasets I am getting different distribution for same data.

I am doing something like this:

ArrayOfDoublesSketch unionSketch = getUnionOfSketches(List<ArrayOfDoublesSketch>  list);

ArrayOfDoublesSketch result = unionSketch.getResult() ;
UpdateDoublesSketch quantilesSketch = DoublesSketch.builder().build();
        ArrayOfDoublesSketchIterator itr =result.iterator();
        while (itr.next()) {
            quantilesSketch.update(itr.getValues()[0]);
        }
        double [] fr = quantilesSketch.getPMF(new double[] {1.0, 2.0, 3.0, 4.0, 5.0,6.0,7.0,8.0});

public static ArrayOfDoublesUnion getUnionOfSketches(List<ArrayOfDoublesSketch> arrayOfDoublesSketches ){
        ArrayOfDoublesUnion union = new ArrayOfDoublesSetOperationBuilder().buildUnion();
        for(ArrayOfDoublesSketch arrayOfDoublesSketch: arrayOfDoublesSketches){
            union.update(arrayOfDoublesSketch);
        }
        return  union;
    }

In fr[] I am getting different values for same data on multiple runs. Basically the values are oscillating between 2-3 values.

**Comment by AlexanderSaydakov** [comment]
You are using approximate algorithms, so the results can be different every time. The question is how different are they? What accuracy do you expect? To answer this question you need to be more specific. What do you mean by "oscillating between 2-3 values"? What is the true distribution of your input data? What approximation are you getting? Why do you think it is too far off?

**Comment by leerho** [comment]
Priyam,

There are a number of problems with the code you provided:
1.  First it is filled with errors.  It took me a while for me to figure
out what you *might* be trying to do.
2.  As Alex points out, you leave out so much information, that we are left
to guessing what you are up to.
3.  Why are you using a tuple sketch at all?  If you have a stream of
double values that you want to understand the distribution of, why not just
send them directly to one of the quantiles sketches.
4.  Your code is effectively doing double sampling of your data, first by
the tuple sketch (which by default keeps 4096 samples), and the sampling
that with the quantiles sketch (which by default keeps only 128 values).
This will make the error bounds on the quantile sketch meaningless and it
will be much worse.  You should at least increase the K value of the
quantile sketch to be much larger, preferably at least as large as the
configured size of the tuple sketch.
5.  The ArrayOfDoublesSketch is an aggregating sketch. This means that if
there are any duplicate keys in your stream, the value retained in the
sketch will be the sum.  Is this what you want? Only if you want to obtain
the "distribution of sums" will this make any sense.

If you can be much more clear about what you are trying to do and the
nature of your input stream, we could be more helpful.

Cheers,

Lee.

**Comment by priyamgupta01** [comment]
Hi Rhodes/Alexander

Thanks for your findings/suggestion.
You might have faced issues in compiling as I have shared the relevant code
from different modules.

Here is brief of why I am using both tuple and quantile sketch.
I have timeseries list of  users in different windows. I need to find the
distribution of users who appeared in multiple windows.
What I did is assigned value 1 to each user in tuple sketch and then merged
to find that a same user appeared in how many windows. Then this sketch is
passed to quantile sketch to get the distribution.

Your suggestion in 4th point helped me to solve the problem. I increased
the value of k to 4096.

Here is the brief of issue that I faced:

When I run the code with same set of data multiple times, what I observed
was that distribution gets changed Everytime. For eg:
1st run
user count appearing in 3 windows=3446
user count appearing in 4
windows=1000

2nd run
user count appearing in 3 windows=3646
user count appearing in 4 windows=800


Total count was same but distribution was getting rearranged.





Thanks,
Priyam

**Comment by leerho** [comment]
@priyamgupta01 
Ah, now I think I understand what you are trying to do.  You might take a look at [Tuple Sketch Engagement Example]
 (https://datasketches.github.io/docs/Tuple/TupleEngagementExample.html), which sounds similar. This gives you a distribution, but is focused on the "most-frequent" users across the time periods.  The accuracy is best on the most frequent users and worst on the rarely-occurring users.  It doesn't use the quantile sketch at all.

**Comment by leerho** [comment]
It appears that this issue has been resolved without any required changes in the code, so I'm going to close it.  We can reopen if needed.
