### ISSUE TITLE
Does Union support multi Sketch flavor updates?

### ISSUE THREAD

**Issue by jdob2** [apache/incubator-datasketches-java#301]
I am trying to understand why the following code doesn't work as intended

Version
        
     <groupId>com.yahoo.datasketches</groupId>
     <artifactId>sketches-core</artifactId>
     <version>0.12.0</version>

Code

        Union set1 = Union.builder().setNominalEntries(4096).buildUnion();
        set1.update(1);
        set1.update(2);
        set1.update(3);
        set1.update(4);
        set1.update(5);
        set1.update(6);
        set1.update(6);
        set1.update(6);

        Union set2 = Union.builder().setNominalEntries(4096).buildUnion();
        set2.update(1);

        AnotB aNotB = Sketches.setOperationBuilder().setNominalEntries(4096).buildANotB();
        aNotB.update(set1.getResult(), set2.getResult());
        System.out.println(aNotB.getResult().getEstimate());

        Union finalUnion = Union.builder().setNominalEntries(4096).buildUnion();
        finalUnion.update(aNotB.getResult());
        System.out.println(finalUnion.getResult().getEstimate());

I am expecting the printout to be 

`5.0`
`5.0`

but instead I get

`5.0`
`0.0`

I must be doing something trivially wrong, or does Union update only support compactSketch from Union?

**Comment by leerho** [comment]
As stated in the [documentation](https://datasketches.apache.org/api/java/snapshot/apidocs/index.html), the AnotB operation is not iterative like Intersection and Union.  It is a stateless function that resets after the getResult.   So your second call to aNotB returns 0.   So instead of your code try this:

```
AnotB aNotB = SetOperationBuilder.buildAnotB();
aNotB.update(SketchA, SketchB); //Called only once.
CompactSketch result = aNotB.getResult();
System.out.println(result.getEstimate());

Union finalUnion = Union.builder().setNominalEntries(4096).buildUnion();
finalUnion.update(result);
System.out.println(finalUnion.getResult().getEstimate());
```

**Comment by leerho** [comment]
You can also do this:
```
AnotB aNotB = SetOperationBuilder.buildAnotB();
CompactSketch result = aNotB.aNotB(SketchA, SketchB);
System.out.println(result.getEstimate());
   ...
```

**Comment by jdob2** [comment]
Ah, you are absolutely correct, that make alot of sense, thanks
